github: [metadata]
remote_theme: "mmistakes/minimal-mistakes@4.23.0"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
title: "Growing Microgreens"
subtitle: "Version 2.0"
repository: "mgfarmer/mg"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-titles-from-headings

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false